source: app
environment: production
# To exclude inside app/
baseurl: http://wegomajor.com
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /insights/:title/

# Collection definition

collections:
  case_studies:
    output: true
