source: app
environment: production
# To exclude inside app/
baseurl: http://wegomajor.com
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /insights/:title/

# Collection definition

collections:
  case_studies:
    output: true


# ############## #
#    CLIENTS
clients:
  -
    name: Wodify
    url: https://www.wodify.com/
    image: /assets/graphics/content/wodify_logo.png
    featured: true
  -
    name: Developmentseed
    url: https://developmentseed.org//
    image: /assets/graphics/content/devseed_logo.png
    featured: true
  -
    name: CTT
    url: http://www.ctt.pt/home/index.html
    image: /assets/graphics/content/ctt_logo.png
    featured: true
  -
    name: Elsie
    url: https://elsie.pt/
    image: /assets/graphics/content/elsie_logo.png
    featured: true
  -
    name: Dott
    url: https://www.dott.pt/
    image: /assets/graphics/content/dott_logo.png
    featured: true
  -
    name: Bright Pixel
    url: https://brpx.com/
    image: /assets/graphics/content/brpx_logo.png
    featured: true
  -
    name: AMT
    url: https://www.amt-autoridade.pt/
    image: /assets/graphics/content/amt_logo.png
    featured: true
  -
    name: BloombergNEF
    url: https://about.bnef.com/
    image: /assets/graphics/content/bloombergNEF_logo.png
    featured: true
  -
    name: HOT
    url: https://www.hotosm.org/
    image: /assets/graphics/content/hot_logo.png
    featured: true
  -
    name: Speak
    url: https://www.speak.social
    image: /assets/graphics/content/speak_logo.png
    featured: true
  -
    name: OpenAQ
    url: https://openaq.org/
    image: /assets/graphics/content/openaq_logo.png
    featured: true
