source: app
environment: production
# To exclude inside app/
baseurl: http://wegomajor.com
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collection definition

collections:
  case_studies:
    output: true
