# ssh-keygen -t rsa -b 4096 -C leihla/major -f deploy_key
version: 2
jobs:
  build:
    docker:
      - image: starefossen/ruby-node:2-6

    working_directory: ~/repo

    environment:
      - DEPLOY_BRANCH: master
      - GH_REF: git@github.com:leihla/major.git
      - GH_NAME: "Major CI"
      - GH_EMAIL: "ci@wegomajor.com"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - add_ssh_keys:
          fingerprints:
            - "cd:13:87:e9:fa:19:89:71:ad:a7:05:e0:41:ab:51:cf"

      - run: 
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              yarn build
            else
              echo "Skip building site"
            fi

      - run:
          name: Deploy to GH Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              cd _site
              git init
              git config user.name "$GH_NAME"
              git config user.email "$GH_EMAIL"
              git add .
              git commit -m "CI deploy [skip ci]"
              git remote add origin $GH_REF
              git push origin --force --quiet HEAD:gh-pages
              rm -rf .git
            else
              echo "Skip deploying to Github"
            fi