# ssh-keygen -t rsa -b 4096 -C leihla/major -f deploy_key

# YAML anchors for base definitions
base_def: &base_def
  docker:
    - image: starefossen/ruby-node:2-8
      environment:
        STAGING_BRANCH: develop
        PRODUCTION_BRANCH: master
        GH_REF: git@github.com:leihla/major.git
        GH_NAME: "Major CI"
        GH_EMAIL: "ci@wegomajor.com"
  working_directory: ~/repo

restore_cache_def: &restore_cache_def
  # Download and cache dependencies
  keys:
  - v1-dependencies-{{ checksum "package.json" }}
  - v1-dependencies-  # fallback if checksum fails

##
## START Circle CI configuration
##

version: 2.1
jobs:
  prepare:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - .bundle
            - bundle
          key: v1-dependencies-{{ checksum "package.json" }}
  build:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run: 
          name: Build app
          command: |
            yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
              - _site/*
  deploy-prod:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - attach_workspace:
          at: /workspace
      - add_ssh_keys:
          fingerprints:
            - "f6:c6:08:d7:94:1f:2e:0e:75:c4:d6:32:7b:fd:68:26"
      - run:
          name: Deploy to GH Pages
          command: |
            cd /workspace/_site
            git init
            git config user.name "$GH_NAME"
            git config user.email "$GH_EMAIL"
            git add .
            git commit -m "CI deploy [skip ci]"
            git remote add origin $GH_REF
            git push origin --force --quiet HEAD:gh-pages
            rm -rf .git
  build-stage:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - run:
          name: Build app
          command: |
            yarn build-stage
      - persist_to_workspace:
          root: ~/repo
          paths:
              - _site/*
  deploy-stage:
    <<: *base_def
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_def
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to surge staging
          command: |
            cp /workspace/_site/index.html /workspace/_site/200.html
            ./node_modules/surge/lib/cli.js --project ./_site --domain major.surge.sh

workflows:
  version: 2
  main:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
          filters:
            branches:
              ignore: develop
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
      - build-stage:
          requires:
            - prepare
          filters:
            branches:
              only: develop
      - deploy-stage:
          requires:
            - build-stage
          filters:
            branches:
              only: develop
